local R

-- TODO: create a readme describing what themes require to be added to the registry.

---@class ThemeRegistryEntry
---@field url string
---@field opts table
---@field pkgname string
---@field dependencies? string[]

---@type table<string, ThemeRegistryEntry>
R = {
  ["tokyonight"] = {
    url = "https://github.com/folke/tokyonight.nvim",
    opts = {},
    pkgname = "tokyonight",
    dependencies = {},
  },
  ["nightfox"] = {
    url = "https://github.com/EdenEast/nightfox.nvim",
    opts = {},
    pkgname = "nightfox",
    dependencies = {},
  },
  ["rose-pine"] = {
    url = "https://github.com/rose-pine/neovim",
    opts = {},
    pkgname = "rose-pine",
    dependencies = {},
  },
  ["witch"] = {
    url = "https://github.com/sontungexpt/witch",
    opts = {},
    pkgname = "witch",
    dependencies = {},
  },
  ["abstract-cs"] = {
    url = "https://github.com/Abstract-IDE/Abstract-cs",
    opts = {},
    pkgname = "abstract-cs",
    dependencies = {},
  },
  ["neon"] = {
    url = "https://github.com/rafamadriz/neon",
    opts = {},
    pkgname = "neon",
    dependencies = {},
  },
  ["vim-code-dark"] = {
    url = "https://github.com/tomasiser/vim-code-dark",
    opts = {},
    pkgname = "vim-code-dark",
    dependencies = {},
  },
  ["vscode"] = {
    url = "https://github.com/Mofiqul/vscode.nvim",
    opts = {},
    pkgname = "vscode",
    dependencies = {},
  },
  ["visual_studio_code"] = {
    url = "https://github.com/askfiy/visual_studio_code",
    opts = {},
    pkgname = "visual_studio_code",
    dependencies = {},
  },
  ["material"] = {
    url = "https://github.com/marko-cerovac/material.nvim",
    opts = {},
    pkgname = "material",
    dependencies = {},
  },
  ["nightfly"] = {
    url = "https://github.com/bluz71/vim-nightfly-colors",
    opts = {},
    pkgname = "nightfly",
    dependencies = {},
  },
  ["moonfly"] = {
    url = "https://github.com/bluz71/vim-moonfly-colors",
    opts = {},
    pkgname = "moonfly",
    dependencies = {},
  },
  ["nvcode"] = {
    url = "https://github.com/ChristianChiarulli/nvcode-color-schemes.vim",
    opts = {},
    pkgname = "nvcode",
    dependencies = {},
  },
  ["evergarden"] = {
    url = "https://github.com/comfysage/evergarden",
    opts = {},
    pkgname = "evergarden",
    dependencies = {},
  },
  ["sonokai"] = {
    url = "https://github.com/sainnhe/sonokai",
    opts = {},
    pkgname = "sonokai",
    dependencies = {},
  },
  ["oxocarbon"] = {
    url = "https://github.com/nyoom-engineering/oxocarbon.nvim",
    opts = {},
    pkgname = "oxocarbon",
    dependencies = {},
  },
  ["blue-moon"] = {
    url = "https://github.com/kyazdani42/blue-moon",
    opts = {},
    pkgname = "blue-moon",
    dependencies = {},
  },
  ["oceanic-next"] = {
    url = "https://github.com/mhartington/oceanic-next",
    opts = {},
    pkgname = "oceanic-next",
    dependencies = {},
  },
  ["zephyr"] = {
    url = "https://github.com/nvimdev/zephyr-nvim",
    opts = {},
    pkgname = "zephyr",
    dependencies = {},
  },
  ["boo"] = {
    url = "https://github.com/rockerBOO/boo-colorscheme-nvim",
    opts = {},
    pkgname = "boo",
    dependencies = {},
  },
  ["ariake"] = {
    url = "https://github.com/jim-at-jibba/ariake.nvim",
    opts = {},
    pkgname = "ariake",
    dependencies = {},
  },
  ["onebuddy"] = {
    url = "https://github.com/Th3Whit3Wolf/onebuddy",
    opts = {},
    pkgname = "onebuddy",
    dependencies = { "tjdevries/colorbuddy.vim" },
  },
  ["modus"] = {
    url = "https://github.com/ishan9299/modus-theme-vim",
    opts = {},
    pkgname = "modus",
    dependencies = {},
  },
  ["edge"] = {
    url = "https://github.com/sainnhe/edge",
    opts = {},
    pkgname = "edge",
    dependencies = {},
  },
  ["deus"] = {
    url = "https://github.com/theniceboy/nvim-deus",
    opts = {},
    pkgname = "deus",
    dependencies = {},
  },
  ["gloombuddy"] = {
    url = "https://github.com/bkegley/gloombuddy",
    opts = {},
    pkgname = "gloombuddy",
    dependencies = { "tjdevries/colorbuddy.vim" },
  },
  ["one"] = {
    url = "https://github.com/Th3Whit3Wolf/one-nvim",
    opts = {},
    pkgname = "one",
    dependencies = {},
  },
  ["hybrid"] = {
    url = "https://github.com/PHSix/nvim-hybrid",
    opts = {},
    pkgname = "hybrid",
    dependencies = {},
  },
  ["space"] = {
    url = "https://github.com/Th3Whit3Wolf/space-nvim",
    opts = {},
    pkgname = "space",
    dependencies = {},
  },
  ["omni"] = {
    url = "https://github.com/yonlu/omni.vim",
    opts = {},
    pkgname = "omni",
    dependencies = {},
  },
  ["aurora"] = {
    url = "https://github.com/ray-x/aurora",
    opts = {},
    pkgname = "aurora",
    dependencies = {},
  },
  ["starry"] = {
    url = "https://github.com/ray-x/starry.nvim",
    opts = {},
    pkgname = "starry",
    dependencies = {},
  },
  ["monokai"] = {
    url = "https://github.com/tanvirtin/monokai.nvim",
    opts = {},
    pkgname = "monokai",
    dependencies = {},
  },
  ["ofirkai"] = {
    url = "https://github.com/ofirgall/ofirkai.nvim",
    opts = {},
    pkgname = "ofirkai",
    dependencies = {},
  },
  ["melange"] = {
    url = "https://github.com/savq/melange-nvim",
    opts = {},
    pkgname = "melange",
    dependencies = {},
  },
  ["base16"] = {
    url = "https://github.com/RRethy/base16-nvim",
    opts = {},
    pkgname = "base16",
    dependencies = {},
  },
  ["falcon"] = {
    url = "https://github.com/fenetikm/falcon",
    opts = {},
    pkgname = "falcon",
    dependencies = {},
  },
  ["nord-esque"] = {
    url = "https://github.com/andersevenrud/nordic.nvim",
    opts = {},
    pkgname = "nord-esque",
    dependencies = {},
  },
  ["nordic"] = {
    url = "https://github.com/AlexvZyl/nordic.nvim",
    opts = {},
    pkgname = "nordic",
    dependencies = {},
  },
  ["nord"] = {
    url = "https://github.com/shaunsingh/nord.nvim",
    opts = {},
    pkgname = "nord",
    dependencies = {},
  },
  ["neosolarized"] = {
    url = "https://github.com/svrana/neosolarized.nvim",
    opts = {},
    pkgname = "neosolarized",
    dependencies = { "tjdevries/colorbuddy.vim" },
  },
  ["solarized"] = {
    url = "https://github.com/ishan9299/nvim-solarized-lua",
    opts = {},
    pkgname = "solarized",
    dependencies = {},
  },
  ["lavender"] = {
    url = "https://codeberg.org/jthvai/lavender.nvim",
    opts = {},
    pkgname = "lavender",
    dependencies = {},
  },
  ["onedark"] = {
    url = "https://github.com/navarasu/onedark.nvim",
    opts = {},
    pkgname = "onedark",
    dependencies = {},
  },
  ["github"] = {
    url = "https://github.com/projekt0n/github-nvim-theme",
    opts = {},
    pkgname = "github",
    dependencies = {},
  },
  ["gruvbox-material"] = {
    url = "https://github.com/sainnhe/gruvbox-material",
    opts = {},
    pkgname = "gruvbox-material",
    dependencies = {},
  },
  ["everforest"] = {
    url = "https://github.com/sainnhe/everforest",
    opts = {},
    pkgname = "everforest",
    dependencies = {},
  },
  ["everforest-lua"] = {
    url = "https://github.com/neanias/everforest-nvim",
    opts = {},
    pkgname = "everforest-lua",
    dependencies = {},
  },
  ["doom-one"] = {
    url = "https://github.com/NTBBloodbath/doom-one.nvim",
    opts = {},
    pkgname = "doom-one",
    dependencies = {},
  },
  ["dracula"] = {
    url = "https://github.com/dracula/vim",
    opts = {},
    pkgname = "dracula",
    dependencies = {},
  },
  ["dracula-lua"] = {
    url = "https://github.com/Mofiqul/dracula.nvim",
    opts = {},
    pkgname = "dracula-lua",
    dependencies = {},
  },
  ["calvera-dark"] = {
    url = "https://github.com/niyabits/calvera-dark.nvim",
    opts = {},
    pkgname = "calvera-dark",
    dependencies = {},
  },
  ["vn-night"] = {
    url = "https://github.com/nxvu699134/vn-night.nvim",
    opts = {},
    pkgname = "vn-night",
    dependencies = {},
  },
  ["codeschool"] = {
    url = "https://github.com/adisen99/codeschool.nvim",
    opts = {},
    pkgname = "codeschool",
    dependencies = { "rktjmp/lush.nvim" },
  },
  ["monochrome"] = {
    url = "https://github.com/kdheepak/monochrome.nvim",
    opts = {},
    pkgname = "monochrome",
    dependencies = {},
  },
  ["zenbones"] = {
    url = "https://github.com/mcchrish/zenbones.nvim",
    opts = {},
    pkgname = "zenbones",
    dependencies = { "rktjmp/lush.nvim" },
  },
  ["catppuccin"] = {
    url = "https://github.com/catppuccin/nvim",
    opts = {},
    pkgname = "catppuccin",
    dependencies = {},
  },
  ["aquarium"] = {
    url = "https://github.com/FrenzyExists/aquarium-vim",
    opts = {},
    pkgname = "aquarium",
    dependencies = {},
  },
  ["substrata"] = {
    url = "https://github.com/kvrohit/substrata.nvim",
    opts = {},
    pkgname = "substrata",
    dependencies = {},
  },
  ["vimdark"] = {
    url = "https://github.com/ldelossa/vimdark",
    opts = {},
    pkgname = "vimdark",
    dependencies = {},
  },
  ["everblush"] = {
    url = "https://github.com/Everblush/nvim",
    opts = {},
    pkgname = "everblush",
    dependencies = {},
  },
  ["apprentice"] = {
    url = "https://github.com/adisen99/apprentice.nvim",
    opts = {},
    pkgname = "apprentice",
    dependencies = { "rktjmp/lush.nvim" },
  },
  ["onedarkpro"] = {
    url = "https://github.com/olimorris/onedarkpro.nvim",
    opts = {},
    pkgname = "onedarkpro",
    dependencies = {},
  },
  ["onenord"] = {
    url = "https://github.com/rmehri01/onenord.nvim",
    opts = {},
    pkgname = "onenord",
    dependencies = {},
  },
  ["gruvy"] = {
    url = "https://github.com/RishabhRD/gruvy",
    opts = {},
    pkgname = "gruvy",
    dependencies = { "rktjmp/lush.nvim" },
  },
  ["gruvbox-baby"] = {
    url = "https://github.com/luisiacc/gruvbox-baby",
    opts = {},
    pkgname = "gruvbox-baby",
    dependencies = {},
  },
  ["zephyrium"] = {
    url = "https://github.com/titanzero/zephyrium",
    opts = {},
    pkgname = "zephyrium",
    dependencies = {},
  },
  ["kanagawa"] = {
    url = "https://github.com/rebelot/kanagawa.nvim",
    opts = {},
    pkgname = "kanagawa",
    dependencies = {},
  },
  ["kurayami"] = {
    url = "https://github.com/kevinm6/kurayami.nvim",
    opts = {},
    pkgname = "kurayami",
    dependencies = {},
  },
  ["tokyodark"] = {
    url = "https://github.com/tiagovla/tokyodark.nvim",
    opts = {},
    pkgname = "tokyodark",
    dependencies = {},
  },
  ["one-monokai"] = {
    url = "https://github.com/cpea2506/one_monokai.nvim",
    opts = {},
    pkgname = "one-monokai",
    dependencies = {},
  },
  ["rasmus"] = {
    url = "https://github.com/kvrohit/rasmus.nvim",
    opts = {},
    pkgname = "rasmus",
    dependencies = {},
  },
  ["paramount-ng"] = {
    url = "https://github.com/chrsm/paramount-ng.nvim",
    opts = {},
    pkgname = "paramount-ng",
    dependencies = { "rktjmp/lush.nvim" },
  },
  ["juliana"] = {
    url = "https://github.com/kaiuri/nvim-juliana",
    opts = {},
    pkgname = "juliana",
    dependencies = {},
  },
  ["kimbox"] = {
    url = "https://github.com/lmburns/kimbox",
    opts = {},
    pkgname = "kimbox",
    dependencies = {},
  },
  ["arctic"] = {
    url = "https://github.com/rockyzhang24/arctic.nvim",
    opts = {},
    pkgname = "arctic",
    dependencies = { "rktjmp/lush.nvim" },
  },
  ["mellifluous"] = {
    url = "https://github.com/ramojus/mellifluous.nvim",
    opts = {},
    pkgname = "mellifluous",
    dependencies = {},
  },
  ["minimal"] = {
    url = "https://github.com/Yazeed1s/minimal.nvim",
    opts = {},
    pkgname = "minimal",
    dependencies = {},
  },
  ["sherbet"] = {
    url = "https://github.com/lewpoly/sherbet.nvim",
    opts = {},
    pkgname = "sherbet",
    dependencies = {},
  },
  ["adwaita"] = {
    url = "https://github.com/Mofiqul/adwaita.nvim",
    opts = {},
    pkgname = "adwaita",
    dependencies = {},
  },
  ["poimandres"] = {
    url = "https://github.com/olivercederborg/poimandres.nvim",
    opts = {},
    pkgname = "poimandres",
    dependencies = {},
  },
  ["mellow"] = {
    url = "https://github.com/mellow-theme/mellow.nvim",
    opts = {},
    pkgname = "mellow",
    dependencies = {},
  },
  ["lucy"] = {
    url = "https://github.com/Yazeed1s/oh-lucy.nvim",
    opts = {},
    pkgname = "lucy",
    dependencies = {},
  },
  ["embark"] = {
    url = "https://github.com/embark-theme/vim",
    opts = {},
    pkgname = "embark",
    dependencies = {},
  },
  ["nvimgelion"] = {
    url = "https://github.com/nyngwang/nvimgelion",
    opts = {},
    pkgname = "nvimgelion",
    dependencies = {},
  },
  ["fluoromachine"] = {
    url = "https://github.com/maxmx03/fluoromachine.nvim",
    opts = {},
    pkgname = "fluoromachine",
    dependencies = {},
  },
  ["midnight"] = {
    url = "https://github.com/dasupradyumna/midnight.nvim",
    opts = {},
    pkgname = "midnight",
    dependencies = {},
  },
  ["yawnc"] = {
    url = "https://github.com/sonjiku/yawnc.nvim",
    opts = {},
    pkgname = "yawnc",
    dependencies = {},
  },
  ["dark-flat"] = {
    url = "https://github.com/uncleTen276/dark_flat.nvim",
    opts = {},
    pkgname = "dark-flat",
    dependencies = {},
  },
  ["citruszest"] = {
    url = "https://github.com/zootedb0t/citruszest.nvim",
    opts = {},
    pkgname = "citruszest",
    dependencies = {},
  },
  ["vitesse"] = {
    url = "https://github.com/2nthony/vitesse.nvim",
    opts = {},
    pkgname = "vitesse",
    dependencies = { "tjdevries/colorbuddy.vim" },
  },
  ["miasma"] = {
    url = "https://github.com/xero/miasma.nvim",
    opts = {},
    pkgname = "miasma",
    dependencies = {},
  },
  ["deepwhite"] = {
    url = "https://github.com/Verf/deepwhite.nvim",
    opts = {},
    pkgname = "deepwhite",
    dependencies = {},
  },
  ["ronny"] = {
    url = "https://github.com/judaew/ronny.nvim",
    opts = {},
    pkgname = "ronny",
    dependencies = {},
  },
  ["bamboo"] = {
    url = "https://github.com/ribru17/bamboo.nvim",
    opts = {},
    pkgname = "bamboo",
    dependencies = {},
  },
  ["nightcity"] = {
    url = "https://github.com/cryptomilk/nightcity.nvim",
    opts = {},
    pkgname = "nightcity",
    dependencies = {},
  },
  ["monokai-nightasty"] = {
    url = "https://github.com/polirritmico/monokai-nightasty.nvim",
    opts = {},
    pkgname = "monokai-nightasty",
    dependencies = {},
  },
  ["night-owl"] = {
    url = "https://github.com/oxfist/night-owl.nvim",
    opts = {},
    pkgname = "night-owl",
    dependencies = {},
  },
  ["modus-contrast"] = {
    url = "https://github.com/miikanissi/modus-themes.nvim",
    opts = {},
    pkgname = "modus-contrast",
    dependencies = {},
  },
  ["palenight"] = {
    url = "https://github.com/alexmozaidze/palenight.nvim",
    opts = {},
    pkgname = "palenight",
    dependencies = {},
  },
  ["cyberdream"] = {
    url = "https://github.com/scottmckendry/cyberdream.nvim",
    opts = {},
    pkgname = "cyberdream",
    dependencies = {},
  },
  ["hybrid-dark"] = {
    url = "https://github.com/HoNamDuong/hybrid.nvim",
    opts = {},
    pkgname = "hybrid-dark",
    dependencies = {},
  },
  ["halfspace"] = {
    url = "https://gitlab.com/sxwpb/halfspace.nvim",
    opts = {},
    pkgname = "halfspace",
    dependencies = {},
  },
  ["distinct"] = {
    url = "https://gitlab.com/bartekjaszczak/distinct-nvim",
    opts = {},
    pkgname = "distinct",
    dependencies = {},
  },
  ["synthweave"] = {
    url = "https://github.com/samharju/synthweave.nvim",
    opts = {},
    pkgname = "synthweave",
    dependencies = {},
  },
  ["darkearth"] = {
    url = "https://github.com/ptdewey/darkearth-nvim",
    opts = {},
    pkgname = "darkearth",
    dependencies = { "rktjmp/lush.nvim" },
  },
  ["bluloco"] = {
    url = "https://github.com/uloco/bluloco.nvim",
    opts = {},
    pkgname = "bluloco",
    dependencies = { "rktjmp/lush.nvim" },
  },
  ["gruvbox"] = {
    url = "https://github.com/ellisonleao/gruvbox.nvim",
    opts = {},
    pkgname = "gruvbox",
    dependencies = {},
  },
  ["jellybeans"] = {
    url = "https://github.com/metalelf0/jellybeans-nvim",
    opts = {},
    pkgname = "jellybeans",
    dependencies = { "rktjmp/lush.nvim" },
  },
  ["cobalt"] = {
    url = "https://github.com/lalitmee/cobalt2.nvim",
    opts = {},
    pkgname = "cobalt",
    dependencies = { "tjdevries/colorbuddy.vim" },
  },
  ["selenized"] = {
    url = "https://github.com/calind/selenized.nvim",
    opts = {},
    pkgname = "selenized",
    dependencies = {},
  },
  ["sunburn"] = {
    url = "https://github.com/loganswartz/sunburn.nvim",
    opts = {},
    pkgname = "sunburn",
    dependencies = { "loganswartz/polychrome.nvim" },
  },
}

return R
